"""Genetic programming primitives and helpers for arrangement tweaks."""

from .engine import (
    EngineConfig,
    EngineHooks,
    EngineResult,
    EngineState,
    LocalSearchBudgets,
    SpanEvaluation,
    evaluate_spans,
    run_engine,
)
from .explain import explain_program
from .init import generate_random_program, seed_programs, translate_salvage_trace
from .ops import (
    ChoiceDomain,
    GPPrimitive,
    GlobalTranspose,
    LocalOctave,
    ParameterDomain,
    RangeDomain,
    SimplifyRhythm,
    SpanDescriptor,
)
from .repair import repair_program
from .session import GPSessionConfig, GPSessionLog, GPSessionResult, run_gp_session
from .selection import (
    Individual,
    SelectionConfig,
    advance_generation,
    crowding_distance,
    nondominated_sort,
    select_population,
    update_archive,
)
from .strategy import GPArrangementStrategyResult, GPInstrumentCandidate, arrange_v3_gp
from .validation import (
    ParameterValidationError,
    ProgramConstraints,
    ProgramLengthError,
    ProgramValidationError,
    SpanLimitError,
    SpanResolutionError,
    WindowLimitError,
    merge_constraints,
    validate_program,
)
from .variation import (
    GPProgram,
    crossover_by_span,
    mutate_delete,
    mutate_insert,
    mutate_program,
    mutate_tweak,
    one_point_crossover,
)

__all__ = [
    "ChoiceDomain",
    "EngineConfig",
    "EngineHooks",
    "EngineResult",
    "EngineState",
    "GPPrimitive",
    "GlobalTranspose",
    "LocalOctave",
    "ParameterDomain",
    "explain_program",
    "generate_random_program",
    "GPSessionConfig",
    "GPSessionLog",
    "GPSessionResult",
    "ProgramConstraints",
    "ProgramLengthError",
    "ProgramValidationError",
    "RangeDomain",
    "seed_programs",
    "SimplifyRhythm",
    "SpanDescriptor",
    "SpanEvaluation",
    "SpanLimitError",
    "SpanResolutionError",
    "WindowLimitError",
    "merge_constraints",
    "ParameterValidationError",
    "translate_salvage_trace",
    "repair_program",
    "GPProgram",
    "crossover_by_span",
    "mutate_delete",
    "mutate_insert",
    "mutate_program",
    "mutate_tweak",
    "one_point_crossover",
    "run_engine",
    "LocalSearchBudgets",
    "evaluate_spans",
    "validate_program",
    "Individual",
    "SelectionConfig",
    "advance_generation",
    "crowding_distance",
    "nondominated_sort",
    "select_population",
    "update_archive",
    "run_gp_session",
    "arrange_v3_gp",
    "GPInstrumentCandidate",
    "GPArrangementStrategyResult",
]
